### ISSUE TITLE
Filter out hosts with a version number below 1.3.7

### ISSUE THREAD

**Issue by Fornax96** [SiaHubLab/siahub#36]
Hosts which are running a Sia version below 1.3.7 are not actually on the Sia network but on Sia classic instead. Removing these hosts from SiaHub will clean the host database up a lot be removing hosts which are not actually active anymore.

This will also remove [this host](https://siahub.info/host/1627) which pretends to have 1.1 PB of storage space. Which will in turn make the statistics on the network page more realistic.

**Comment by S-anasol** [comment]
Why wallet keep it in DB then? 
Shouldn't it automatically remove it?

Since I don't have such possibility actually, that's just sia wallet...

Only way is remove hostdb, which will send to offline all hosts probably for sometime

**Comment by S-anasol** [comment]
@Fornax96 what you think? :)

**Comment by Fornax96** [comment]
Oh sorry I went on vacation shortly after submitting this bug.

Sia 1.4.0 compensates by putting the 1.3.6 and lower hosts all the way at the bottom of the hostdb list. But even if the hosts have no chance of ever being picked when forming contracts, they still count towards the total on siahub.

For Sia itself it's not really important to remove those hosts, but in siahub it skews the reported statistics.

Siahub has its own database which keeps track of these statistics right? You could still show the hosts in the list, just exclude them from the stats. I'm not sure which database siahub uses, but in mysql it should be as easy as adding `WHERE host.version NOT IN('1.3.0', '1.3.1', '1.3.2', '1.3.3', '1.3.4', '1.3.5')`.

**Comment by sanasol** [comment]
Done.

![image](https://user-images.githubusercontent.com/1709666/56141432-76453380-5fa5-11e9-99b1-819aaab18ce0.png)

**Comment by Fornax96** [comment]
Hey, just so you know: Sia 1.4.1 will only use hosts of version 1.4.0 or higher.
