### ISSUE TITLE
Wrong geolocation detected for host

### ISSUE THREAD

**Issue by DaWe35** [SiaHubLab/siahub#37]
Hey!
My host **sia.coolhd.hu:9982** location detected wrongly. As the picture shows, my VPS renter from germany, not from the USA.
https://siahub.info/host/14799

![kép](https://user-images.githubusercontent.com/10603822/70848919-a4eb1500-1e78-11ea-9c1c-20cfd982b96d.png)

**Comment by sanasol** [comment]
Updated geo ip database, fixed.
